<?php

namespace JiraCloud\Test;

use JiraCloud\Dumper;
use PHPUnit\Framework\TestCase;
use JiraCloud\JiraException;
use JiraCloud\Issue\Version;
use JiraCloud\Project\ProjectService;
use JiraCloud\Version\VersionService;

class VersionTest extends TestCase
{
    private $project = 'TEST';

    /**
     * @test
     *
     * @return string
     * @throws \JsonMapper_Exception
     */
    public function create_version() :string
    {
        $versionName = '2.3.4';
        try {
            $projectService = new ProjectService();
            $project = $projectService->get($this->project);

            $versionService = new VersionService();

            $version = new Version();

            $version->setName($versionName)
                    ->setDescription('Generated by script')
                    ->setReleased(true)
                    ->setReleaseDate(new \DateTime())
                    ->setProjectId($project->id);

            $res = $versionService->create($version);

            $this->assertEquals($res->name, $versionName);

            return $versionName;
        } catch (JiraException $e) {
            print("Error Occurred! " . $e->getMessage());
        }

        return $versionName;
    }

    /**
     * @test
     * @depends create_version
     *
     */
    public function update_project_version(string $versionName) : string
    {
        $newVersionName = null;
        try {
            $versionService = new VersionService();
            $projectService = new ProjectService();

            $ver = $projectService->getVersion($this->project, $versionName);

            // change version name
            $newVersionName = $ver->name . ' Updated name';

            $ver->setName($newVersionName)
                ->setDescription($ver->description . ' Updated description')
                ->setReleased(false)
                ->setReleaseDate(
                    (new \DateTime())->add(date_interval_create_from_date_string('1 months 3 days'))
                    );

            $res = $versionService->update($ver);

            $this->assertEquals($res->name, $ver->name);

        } catch (JiraException $e) {
            print("Error Occurred! " . $e->getMessage());
        }

        return $newVersionName;
    }

    /**
     * @test
     * @depends update_project_version
     */
    public function delete_project_version(string $newVersionName)
    {
        try {
            $versionService = new VersionService();
            $projectService = new ProjectService();

            $ver = $projectService->getVersion($this->project, $newVersionName);

            $res = $versionService->delete($ver);

            $this->assertEquals($res, true);
        } catch (JiraException $e) {
            print("Error Occurred! " . $e->getMessage());
        }
    }
}
